name: my_assignment3
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - images/datebg.jpg
    - images/beachbg.jpg
    - images/clockbg.webp
    - images/clock.jpg
    - images/time.jpg
    - images/time1.jpg
    - images/time2.jpeg
    - images/time3.avif
    - images/time4.jpg
    - images/note.avif
    - images/date1.avif
  fonts:
    - family: Angkor
      fonts:
        - asset: fonts/Angkor-Regular.ttf
    - family: Tagesschrift
      fonts:
        - asset: fonts/Tagesschrift-Regular.ttf
